CREATE PACKAGE KONWERSJA IS
    FUNCTION CELS_TO_FAHR(temp NUMBER) RETURN NUMBER;
    FUNCTION FAHR_TO_CELS(temp NUMBER) RETURN NUMBER;
END KONWERSJA;
--
CREATE PACKAGE BODY KONWERSJA IS
    FUNCTION CELS_TO_FAHR(temp NUMBER) RETURN NUMBER IS
    BEGIN
        RETURN 9/5 * temp + 32;
    END CELS_TO_FAHR;
    FUNCTION FAHR_TO_CELS(temp NUMBER) RETURN NUMBER IS
    BEGIN
        RETURN 5/9 * (temp - 32);
    END FAHR_TO_CELS;
END KONWERSJA;
--
SELECT KONWERSJA.FAHR_TO_CELS(212) CELSJUSZ FROM DUAL;
--
SELECT KONWERSJA.CELS_TO_FAHR(0) FAHRENHEIT FROM DUAL; 