CREATE SEQUENCE seq_zesp START WITH 60
INCREMENT BY 10;

CREATE OR REPLACE TRIGGER trig_id_zesp
BEFORE INSERT ON zespoly
FOR EACH ROW
BEGIN
IF (:NEW.id_zesp IS NULL) THEN
    SELECT seq_zesp.NEXTVAL
    INTO :NEW.id_zesp FROM DUAL;
END IF;
END;